version: "2"
services:
  backend:
    build: ./backend
    links:
      - database
      - authenticator
    environment:
      WAIT_HOSTS: database:3306, authenticator:5000
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    links:
      - backend
    stdin_open: true
    tty: true

  authenticator:
    build: ./authenticator
    links:
      - database
    environment:
      WAIT_HOSTS: database:3306
    ports:
      - "5000:5000"

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: unbreakable
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro

  monitoring:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/:/etc/grafana/provisioning



